CREATE TYPE "public"."audit_action" AS ENUM('create', 'update', 'delete', 'resolve');--> statement-breakpoint
CREATE TYPE "public"."conflict_resolution" AS ENUM('kept_existing', 'kept_incoming');--> statement-breakpoint
CREATE TYPE "public"."death_cause" AS ENUM('unknown', 'disease', 'heat', 'culled', 'predator', 'crush');--> statement-breakpoint
CREATE TYPE "public"."feed_kind" AS ENUM('starter', 'grower', 'finisher');--> statement-breakpoint
CREATE TYPE "public"."feed_unit" AS ENUM('bags', 'kg');--> statement-breakpoint
CREATE TYPE "public"."other_sale_kind" AS ENUM('manure');--> statement-breakpoint
CREATE TYPE "public"."payment_method" AS ENUM('cash', 'transfer', 'pos');--> statement-breakpoint
CREATE TYPE "public"."role" AS ENUM('owner', 'manager', 'recorder');--> statement-breakpoint
CREATE TYPE "public"."set_status" AS ENUM('brooding', 'growing', 'selling', 'closed');--> statement-breakpoint
CREATE TYPE "public"."sync_status" AS ENUM('applied', 'conflict', 'rejected');--> statement-breakpoint
CREATE TYPE "public"."water_level" AS ENUM('low', 'normal', 'high');--> statement-breakpoint
CREATE TABLE "invites" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"email" text NOT NULL,
	"role" "role" NOT NULL,
	"token_hash" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"accepted_at" timestamp with time zone,
	"created_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "invites_token_hash_unique" UNIQUE("token_hash")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"password_hash" text NOT NULL,
	"role" "role" NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"last_active_at" timestamp with time zone,
	"invited_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "breed_curves" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"client_id" uuid NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"created_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"name" text NOT NULL,
	"points" jsonb NOT NULL,
	CONSTRAINT "breed_curves_client_id_unique" UNIQUE("client_id")
);
--> statement-breakpoint
CREATE TABLE "sets" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"client_id" uuid NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"created_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"number" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "sets_number_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text,
	"stock_type_id" uuid NOT NULL,
	"pen" text,
	"status" "set_status" DEFAULT 'brooding' NOT NULL,
	"start_date" date NOT NULL,
	"intake" integer NOT NULL,
	"day_old_supplier" text NOT NULL,
	"day_old_unit_cost" bigint NOT NULL,
	"breed_curve_id" uuid NOT NULL,
	"closed_on" date,
	CONSTRAINT "sets_client_id_unique" UNIQUE("client_id"),
	CONSTRAINT "sets_number_unique" UNIQUE("number")
);
--> statement-breakpoint
CREATE TABLE "stock_types" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"client_id" uuid NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"created_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"key" text NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "stock_types_client_id_unique" UNIQUE("client_id"),
	CONSTRAINT "stock_types_key_unique" UNIQUE("key")
);
--> statement-breakpoint
CREATE TABLE "daily_log_conflicts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"set_id" uuid NOT NULL,
	"date" date NOT NULL,
	"incoming" jsonb NOT NULL,
	"existing_id" uuid NOT NULL,
	"mutation_id" uuid NOT NULL,
	"raised_by" uuid NOT NULL,
	"resolved_by" uuid,
	"resolved_at" timestamp with time zone,
	"resolution" "conflict_resolution",
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "daily_log_conflicts_mutation_id_unique" UNIQUE("mutation_id")
);
--> statement-breakpoint
CREATE TABLE "daily_logs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"client_id" uuid NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"created_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"set_id" uuid NOT NULL,
	"date" date NOT NULL,
	"deaths" integer NOT NULL,
	"death_cause" "death_cause",
	"feed_type_id" uuid,
	"feed_qty" numeric(10, 2),
	"feed_unit" "feed_unit" DEFAULT 'bags' NOT NULL,
	"water_level" "water_level",
	"water_litres" integer,
	"temp_c" numeric(4, 1),
	"tags" text[] DEFAULT '{}'::text[] NOT NULL,
	"note" text,
	"entered_offline_at" timestamp with time zone,
	CONSTRAINT "daily_logs_client_id_unique" UNIQUE("client_id"),
	CONSTRAINT "daily_logs_deaths_not_negative" CHECK ("daily_logs"."deaths" >= 0),
	CONSTRAINT "daily_logs_feed_not_negative" CHECK ("daily_logs"."feed_qty" is null or "daily_logs"."feed_qty" >= 0),
	CONSTRAINT "daily_logs_known_tags" CHECK ("daily_logs"."tags" <@ array['coughing','green_stool','lethargy','panting','wet_litter','poor_appetite']::text[])
);
--> statement-breakpoint
CREATE TABLE "weight_samples" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"client_id" uuid NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"created_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"set_id" uuid NOT NULL,
	"date" date NOT NULL,
	"age_days" integer NOT NULL,
	"weights_grams" integer[] NOT NULL,
	"possible_duplicate_of" uuid,
	CONSTRAINT "weight_samples_client_id_unique" UNIQUE("client_id"),
	CONSTRAINT "weight_samples_has_weights" CHECK (cardinality("weight_samples"."weights_grams") >= 1),
	CONSTRAINT "weight_samples_age_not_negative" CHECK ("weight_samples"."age_days" >= 0)
);
--> statement-breakpoint
CREATE TABLE "feed_purchases" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"client_id" uuid NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"created_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"date" date NOT NULL,
	"feed_type_id" uuid NOT NULL,
	"bags" numeric(10, 2) NOT NULL,
	"kg_per_bag" numeric(6, 2) NOT NULL,
	"price_per_bag" bigint NOT NULL,
	"total" bigint NOT NULL,
	"transport_cost" bigint DEFAULT 0 NOT NULL,
	"supplier" text NOT NULL,
	"expense_id" uuid NOT NULL,
	"transport_expense_id" uuid,
	CONSTRAINT "feed_purchases_client_id_unique" UNIQUE("client_id"),
	CONSTRAINT "feed_purchases_expense_id_unique" UNIQUE("expense_id"),
	CONSTRAINT "feed_purchases_transport_expense_id_unique" UNIQUE("transport_expense_id"),
	CONSTRAINT "feed_purchases_bags_positive" CHECK ("feed_purchases"."bags" > 0),
	CONSTRAINT "feed_purchases_amounts_agree" CHECK (abs("feed_purchases"."total" - "feed_purchases"."bags" * "feed_purchases"."price_per_bag") <= greatest(1, "feed_purchases"."bags" / 2, "feed_purchases"."price_per_bag" * 0.005))
);
--> statement-breakpoint
CREATE TABLE "feed_types" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"client_id" uuid NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"created_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"kind" "feed_kind" NOT NULL,
	"brand" text NOT NULL,
	"kg_per_bag" numeric(6, 2) DEFAULT 25 NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	CONSTRAINT "feed_types_client_id_unique" UNIQUE("client_id")
);
--> statement-breakpoint
CREATE TABLE "ingredient_purchases" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"client_id" uuid NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"created_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"date" date NOT NULL,
	"set_id" uuid NOT NULL,
	"ingredient" text NOT NULL,
	"quantity" numeric(10, 2) NOT NULL,
	"unit" text NOT NULL,
	"unit_cost" bigint NOT NULL,
	"total" bigint NOT NULL,
	"expense_id" uuid NOT NULL,
	CONSTRAINT "ingredient_purchases_client_id_unique" UNIQUE("client_id"),
	CONSTRAINT "ingredient_purchases_expense_id_unique" UNIQUE("expense_id")
);
--> statement-breakpoint
CREATE TABLE "health_records" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"client_id" uuid NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"created_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"set_id" uuid NOT NULL,
	"date" date NOT NULL,
	"item" text NOT NULL,
	"dose" text NOT NULL,
	"cost" bigint,
	"reason" text NOT NULL,
	"set_vaccine_id" uuid,
	"expense_id" uuid,
	CONSTRAINT "health_records_client_id_unique" UNIQUE("client_id"),
	CONSTRAINT "health_records_expense_id_unique" UNIQUE("expense_id")
);
--> statement-breakpoint
CREATE TABLE "set_vaccines" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"client_id" uuid NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"created_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"set_id" uuid NOT NULL,
	"item" text NOT NULL,
	"dose_no" integer NOT NULL,
	"due_age_days" integer NOT NULL,
	"given_on" date,
	"given_by" uuid,
	"note" text,
	CONSTRAINT "set_vaccines_client_id_unique" UNIQUE("client_id")
);
--> statement-breakpoint
CREATE TABLE "vaccine_schedule_defaults" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"client_id" uuid NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"created_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"item" text NOT NULL,
	"dose_no" integer NOT NULL,
	"due_age_days" integer NOT NULL,
	"method" text NOT NULL,
	CONSTRAINT "vaccine_schedule_defaults_client_id_unique" UNIQUE("client_id")
);
--> statement-breakpoint
CREATE TABLE "buyers" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"client_id" uuid NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"created_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"name" text NOT NULL,
	"phone" text,
	"note" text,
	CONSTRAINT "buyers_client_id_unique" UNIQUE("client_id")
);
--> statement-breakpoint
CREATE TABLE "other_sales" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"client_id" uuid NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"created_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"set_id" uuid NOT NULL,
	"date" date NOT NULL,
	"kind" "other_sale_kind" NOT NULL,
	"amount" bigint NOT NULL,
	CONSTRAINT "other_sales_client_id_unique" UNIQUE("client_id")
);
--> statement-breakpoint
CREATE TABLE "sale_payments" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"client_id" uuid NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"created_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"sale_id" uuid NOT NULL,
	"date" date NOT NULL,
	"amount" bigint NOT NULL,
	"method" "payment_method" NOT NULL,
	CONSTRAINT "sale_payments_client_id_unique" UNIQUE("client_id"),
	CONSTRAINT "sale_payments_positive" CHECK ("sale_payments"."amount" > 0)
);
--> statement-breakpoint
CREATE TABLE "sales" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"client_id" uuid NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"created_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"set_id" uuid NOT NULL,
	"date" date NOT NULL,
	"buyer_id" uuid NOT NULL,
	"birds" integer NOT NULL,
	"price_per_bird" bigint NOT NULL,
	"total" bigint NOT NULL,
	"paid_at_sale" bigint NOT NULL,
	"deposit" bigint DEFAULT 0 NOT NULL,
	"method" "payment_method" NOT NULL,
	"note" text,
	CONSTRAINT "sales_client_id_unique" UNIQUE("client_id"),
	CONSTRAINT "sales_birds_positive" CHECK ("sales"."birds" > 0),
	CONSTRAINT "sales_amounts_agree" CHECK (abs("sales"."total" - "sales"."birds" * "sales"."price_per_bird") * 2 <= greatest("sales"."birds", 2)),
	CONSTRAINT "sales_not_overpaid" CHECK ("sales"."deposit" + "sales"."paid_at_sale" <= "sales"."total")
);
--> statement-breakpoint
CREATE TABLE "expense_categories" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"client_id" uuid NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"created_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"key" text NOT NULL,
	"name" text NOT NULL,
	"is_capital_eligible" boolean DEFAULT false NOT NULL,
	CONSTRAINT "expense_categories_client_id_unique" UNIQUE("client_id"),
	CONSTRAINT "expense_categories_key_unique" UNIQUE("key")
);
--> statement-breakpoint
CREATE TABLE "expenses" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"client_id" uuid NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"created_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"date" date NOT NULL,
	"category_id" uuid NOT NULL,
	"description" text NOT NULL,
	"amount" bigint NOT NULL,
	"set_id" uuid,
	"overhead" boolean DEFAULT false NOT NULL,
	"paid_by_user_id" uuid,
	"receipt_key" text,
	"capital_item" boolean DEFAULT false NOT NULL,
	"spread_over_sets" integer,
	"possible_duplicate_of" uuid,
	CONSTRAINT "expenses_client_id_unique" UNIQUE("client_id"),
	CONSTRAINT "expenses_set_or_overhead" CHECK (("expenses"."set_id" is not null) <> "expenses"."overhead"),
	CONSTRAINT "expenses_amount_positive" CHECK ("expenses"."amount" > 0)
);
--> statement-breakpoint
CREATE TABLE "capital_entries" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"client_id" uuid NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"created_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"shareholder_id" uuid NOT NULL,
	"date" date NOT NULL,
	"amount" bigint NOT NULL,
	"note" text,
	CONSTRAINT "capital_entries_client_id_unique" UNIQUE("client_id")
);
--> statement-breakpoint
CREATE TABLE "cash_reconciliations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"client_id" uuid NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"created_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"date" date NOT NULL,
	"counted_cash" bigint NOT NULL,
	"bank_balance" bigint NOT NULL,
	"expected" bigint NOT NULL,
	"difference" bigint NOT NULL,
	"note" text,
	CONSTRAINT "cash_reconciliations_client_id_unique" UNIQUE("client_id")
);
--> statement-breakpoint
CREATE TABLE "loans" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"client_id" uuid NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"created_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"lender_shareholder_id" uuid NOT NULL,
	"amount" bigint NOT NULL,
	"advanced_on" date NOT NULL,
	"repaid_on" date,
	"rate" numeric(5, 4) DEFAULT 0.16 NOT NULL,
	"wht_rate" numeric(5, 4) DEFAULT 0.1 NOT NULL,
	CONSTRAINT "loans_client_id_unique" UNIQUE("client_id")
);
--> statement-breakpoint
CREATE TABLE "shareholders" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"client_id" uuid NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"created_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"name" text NOT NULL,
	"shares" integer NOT NULL,
	CONSTRAINT "shareholders_client_id_unique" UNIQUE("client_id")
);
--> statement-breakpoint
CREATE TABLE "settings" (
	"key" text PRIMARY KEY NOT NULL,
	"value" jsonb NOT NULL,
	"updated_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "devices" (
	"id" uuid PRIMARY KEY NOT NULL,
	"user_id" uuid NOT NULL,
	"user_agent" text,
	"last_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"pending_count" integer DEFAULT 0 NOT NULL,
	"pending_summary" jsonb DEFAULT '[]'::jsonb NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sync_mutations" (
	"mutation_id" uuid PRIMARY KEY NOT NULL,
	"device_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"type" text NOT NULL,
	"payload_hash" text NOT NULL,
	"status" "sync_status" NOT NULL,
	"entity_table" text,
	"entity_id" uuid,
	"result" jsonb NOT NULL,
	"received_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "audit_events" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"table" text NOT NULL,
	"row_id" uuid NOT NULL,
	"action" "audit_action" NOT NULL,
	"field" text,
	"old_value" jsonb,
	"new_value" jsonb,
	"reason" text,
	"user_id" uuid NOT NULL,
	"device_id" uuid,
	"at" timestamp with time zone DEFAULT now() NOT NULL,
	"entered_offline_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "invites" ADD CONSTRAINT "invites_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_invited_by_users_id_fk" FOREIGN KEY ("invited_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "breed_curves" ADD CONSTRAINT "breed_curves_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sets" ADD CONSTRAINT "sets_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sets" ADD CONSTRAINT "sets_stock_type_id_stock_types_id_fk" FOREIGN KEY ("stock_type_id") REFERENCES "public"."stock_types"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sets" ADD CONSTRAINT "sets_breed_curve_id_breed_curves_id_fk" FOREIGN KEY ("breed_curve_id") REFERENCES "public"."breed_curves"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_types" ADD CONSTRAINT "stock_types_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "daily_log_conflicts" ADD CONSTRAINT "daily_log_conflicts_set_id_sets_id_fk" FOREIGN KEY ("set_id") REFERENCES "public"."sets"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "daily_log_conflicts" ADD CONSTRAINT "daily_log_conflicts_existing_id_daily_logs_id_fk" FOREIGN KEY ("existing_id") REFERENCES "public"."daily_logs"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "daily_log_conflicts" ADD CONSTRAINT "daily_log_conflicts_raised_by_users_id_fk" FOREIGN KEY ("raised_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "daily_log_conflicts" ADD CONSTRAINT "daily_log_conflicts_resolved_by_users_id_fk" FOREIGN KEY ("resolved_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "daily_logs" ADD CONSTRAINT "daily_logs_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "daily_logs" ADD CONSTRAINT "daily_logs_set_id_sets_id_fk" FOREIGN KEY ("set_id") REFERENCES "public"."sets"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "daily_logs" ADD CONSTRAINT "daily_logs_feed_type_id_feed_types_id_fk" FOREIGN KEY ("feed_type_id") REFERENCES "public"."feed_types"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "weight_samples" ADD CONSTRAINT "weight_samples_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "weight_samples" ADD CONSTRAINT "weight_samples_set_id_sets_id_fk" FOREIGN KEY ("set_id") REFERENCES "public"."sets"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "feed_purchases" ADD CONSTRAINT "feed_purchases_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "feed_purchases" ADD CONSTRAINT "feed_purchases_feed_type_id_feed_types_id_fk" FOREIGN KEY ("feed_type_id") REFERENCES "public"."feed_types"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "feed_purchases" ADD CONSTRAINT "feed_purchases_expense_id_expenses_id_fk" FOREIGN KEY ("expense_id") REFERENCES "public"."expenses"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "feed_purchases" ADD CONSTRAINT "feed_purchases_transport_expense_id_expenses_id_fk" FOREIGN KEY ("transport_expense_id") REFERENCES "public"."expenses"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "feed_types" ADD CONSTRAINT "feed_types_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ingredient_purchases" ADD CONSTRAINT "ingredient_purchases_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ingredient_purchases" ADD CONSTRAINT "ingredient_purchases_set_id_sets_id_fk" FOREIGN KEY ("set_id") REFERENCES "public"."sets"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ingredient_purchases" ADD CONSTRAINT "ingredient_purchases_expense_id_expenses_id_fk" FOREIGN KEY ("expense_id") REFERENCES "public"."expenses"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "health_records" ADD CONSTRAINT "health_records_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "health_records" ADD CONSTRAINT "health_records_set_id_sets_id_fk" FOREIGN KEY ("set_id") REFERENCES "public"."sets"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "health_records" ADD CONSTRAINT "health_records_set_vaccine_id_set_vaccines_id_fk" FOREIGN KEY ("set_vaccine_id") REFERENCES "public"."set_vaccines"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "health_records" ADD CONSTRAINT "health_records_expense_id_expenses_id_fk" FOREIGN KEY ("expense_id") REFERENCES "public"."expenses"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "set_vaccines" ADD CONSTRAINT "set_vaccines_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "set_vaccines" ADD CONSTRAINT "set_vaccines_set_id_sets_id_fk" FOREIGN KEY ("set_id") REFERENCES "public"."sets"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "set_vaccines" ADD CONSTRAINT "set_vaccines_given_by_users_id_fk" FOREIGN KEY ("given_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vaccine_schedule_defaults" ADD CONSTRAINT "vaccine_schedule_defaults_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "buyers" ADD CONSTRAINT "buyers_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "other_sales" ADD CONSTRAINT "other_sales_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "other_sales" ADD CONSTRAINT "other_sales_set_id_sets_id_fk" FOREIGN KEY ("set_id") REFERENCES "public"."sets"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sale_payments" ADD CONSTRAINT "sale_payments_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sale_payments" ADD CONSTRAINT "sale_payments_sale_id_sales_id_fk" FOREIGN KEY ("sale_id") REFERENCES "public"."sales"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sales" ADD CONSTRAINT "sales_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sales" ADD CONSTRAINT "sales_set_id_sets_id_fk" FOREIGN KEY ("set_id") REFERENCES "public"."sets"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sales" ADD CONSTRAINT "sales_buyer_id_buyers_id_fk" FOREIGN KEY ("buyer_id") REFERENCES "public"."buyers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "expense_categories" ADD CONSTRAINT "expense_categories_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "expenses" ADD CONSTRAINT "expenses_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "expenses" ADD CONSTRAINT "expenses_category_id_expense_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."expense_categories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "expenses" ADD CONSTRAINT "expenses_set_id_sets_id_fk" FOREIGN KEY ("set_id") REFERENCES "public"."sets"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "expenses" ADD CONSTRAINT "expenses_paid_by_user_id_users_id_fk" FOREIGN KEY ("paid_by_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "capital_entries" ADD CONSTRAINT "capital_entries_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "capital_entries" ADD CONSTRAINT "capital_entries_shareholder_id_shareholders_id_fk" FOREIGN KEY ("shareholder_id") REFERENCES "public"."shareholders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cash_reconciliations" ADD CONSTRAINT "cash_reconciliations_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "loans" ADD CONSTRAINT "loans_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "loans" ADD CONSTRAINT "loans_lender_shareholder_id_shareholders_id_fk" FOREIGN KEY ("lender_shareholder_id") REFERENCES "public"."shareholders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shareholders" ADD CONSTRAINT "shareholders_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "settings" ADD CONSTRAINT "settings_updated_by_users_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "devices" ADD CONSTRAINT "devices_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sync_mutations" ADD CONSTRAINT "sync_mutations_device_id_devices_id_fk" FOREIGN KEY ("device_id") REFERENCES "public"."devices"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sync_mutations" ADD CONSTRAINT "sync_mutations_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_events" ADD CONSTRAINT "audit_events_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "users_email_unique" ON "users" USING btree (lower("email"));--> statement-breakpoint
CREATE INDEX "daily_log_conflicts_open" ON "daily_log_conflicts" USING btree ("set_id") WHERE "daily_log_conflicts"."resolved_at" is null;--> statement-breakpoint
CREATE UNIQUE INDEX "daily_logs_set_date_live" ON "daily_logs" USING btree ("set_id","date") WHERE "daily_logs"."deleted_at" is null;--> statement-breakpoint
CREATE INDEX "weight_samples_set_date" ON "weight_samples" USING btree ("set_id","date");--> statement-breakpoint
CREATE INDEX "feed_purchases_type_date" ON "feed_purchases" USING btree ("feed_type_id","date");--> statement-breakpoint
CREATE INDEX "sale_payments_sale" ON "sale_payments" USING btree ("sale_id");--> statement-breakpoint
CREATE INDEX "sales_set" ON "sales" USING btree ("set_id");--> statement-breakpoint
CREATE INDEX "sales_buyer" ON "sales" USING btree ("buyer_id");--> statement-breakpoint
CREATE INDEX "expenses_date" ON "expenses" USING btree ("date");--> statement-breakpoint
CREATE INDEX "expenses_set" ON "expenses" USING btree ("set_id");--> statement-breakpoint
CREATE INDEX "sync_mutations_received" ON "sync_mutations" USING btree ("received_at");--> statement-breakpoint
CREATE INDEX "audit_events_row" ON "audit_events" USING btree ("table","row_id");